title: Commsunity - The community engagement platform.
baseURL: /
params:
  palette: purple
  header:
    title: Commsunity
    logo_img: /images/commsunity-nobg.png
    has_nav: true
    menu:
      actions:
        - label: Sign Up
          url: /signup
  footer:
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    has_subscribe: true
    social_title: Community
    tagline: Commsunity
    logo_img: /images/commsunity-nobg.png
    has_social: true
    content: "&copy; Commsunity. All rights reserved."
    links:
      - text: Made by Women Can Code
        url: https://www.womencancode.com
        new_window: true
    nav_title: Company
    has_nav: true
disableKinds:
  - RSS
